name: Claude Assistant
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    steps:
      - name: Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN_CUSTOM }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_CUSTOM }}
